### ISSUE TITLE
[Feautre] docker 세팅

### ISSUE THREAD

**Issue by aristo0922** [f-lab-edu/Mytube-streaming#60]

**Comment by aristo0922** [comment]
mytube-backend     | Caused by: java.io.IOException: Cannot run program "/usr/bin/ffmpeg": error=2, No such file or directory



```
ERROR 1 --- [Mytube] [           main] o.s.boot.SpringApplication               : Application run failed

mytube-backend     | 
mytube-backend     | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consumer' defined in URL [jar:nested:/app.jar/!BOOT-INF/classes/!/com/flab/Mytube/kafka/Consumer.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'ffMpeg' defined in class path resource [com/flab/Mytube/config/FFmpegConfig.class]: Failed to instantiate [net.bramp.ffmpeg.FFmpeg]: Factory method 'ffMpeg' threw exception with message: Cannot run program "/usr/bin/ffmpeg": error=2, No such file or directory
mytube-backend     |    at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:795) ~[spring-beans-6.1.6.jar!/:6.1.6]
mytube-backend     |    at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:237) ~[spring-beans-6.1.6.jar!/:6.1.6]
mytube-backend     |    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1355) ~[spring-beans-6.1.6.jar!/:6.1.6]

...


mytube-backend     | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consumer' defined in URL [jar:nested:/app.jar/!BOOT-INF/classes/!/com/flab/Mytube/kafka/Consumer.class]: Unsatisfied dependency expressed through constructor parameter 0: Error creating bean with name 'ffMpeg' defined in class path resource [com/flab/Mytube/config/FFmpegConfig.class]: Failed to instantiate [net.bramp.ffmpeg.FFmpeg]: Factory method 'ffMpeg' threw exception with message: Cannot run program "/usr/bin/ffmpeg": error=2, No such file or directory

```
